USE SAKILA;

#1
SELECT DISTINCT LAST_NAME FROM ACTOR;

#2
SELECT DISTINCT LANGUAGE_ID FROM FILM;

#3
SELECT COUNT(FILM_ID) FROM FILM
WHERE RATING = "PG-13";

# 4
SELECT DISTINCT LENGTH FROM FILM ORDER BY LENGTH DESC LIMIT 10;

#5
SELECT CREATE_DATE FROM CUSTOMER ORDER BY CREATE_DATE ASC LIMIT 1;
SELECT DATEDIFF("2022-07-26 22:04:00", (SELECT CREATE_DATE FROM CUSTOMER ORDER BY CREATE_DATE ASC LIMIT 1));

#6
SELECT *, EXTRACT(MONTH FROM RENTAL_DATE) AS MONTH, DAYOFWEEK(RENTAL_DATE) AS WEEKDAY FROM RENTAL LIMIT 20;

#7
SELECT *, EXTRACT(MONTH FROM RENTAL_DATE) AS MONTH, DAYOFWEEK(RENTAL_DATE) AS WEEKDAY, 
(CASE 
WHEN DAYOFWEEK(RENTAL_DATE) <6 THEN 'WEEKDAY'
ELSE 'WEEKEND'
END) AS DAY_OF_WEEK
FROM RENTAL LIMIT 20;

#8
SELECT RENTAL_DATE FROM RENTAL 
WHERE EXTRACT(MONTH FROM RENTAL_DATE) = EXTRACT(MONTH FROM LAST_UPDATE) 
AND EXTRACT(YEAR FROM RENTAL_DATE) = EXTRACT(YEAR FROM LAST_UPDATE);

#9
SELECT DISTINCT RATING FROM FILM;

#10
SELECT DISTINCT RELEASE_YEAR FROM FILM;

#11
SELECT TITLE FROM FILM WHERE TITLE REGEXP "ARMAGEDDON";

#12
SELECT TITLE FROM FILM WHERE TITLE REGEXP "APOLLO";

#13
SELECT TITLE FROM FILM WHERE TITLE REGEXP "APOLLO$";

#14

SELECT TITLE FROM FILM WHERE TITLE REGEXP '\\bDATE\\b';

#15
SELECT TITLE, LENGTH(TITLE) FROM FILM order by LENGTH(title) DESC limit 10;

#16
SELECT TITLE FROM FILM order by LENGTH DESC limit 10;

#17
SELECT COUNT(FILM_ID) FROM FILM WHERE SPECIAL_FEATURES REGEXP 'BEHIND THE SCENES';
# TEST
# SELECT SPECIAL_FEATURES FROM FILM WHERE SPECIAL_FEATURES REGEXP 'BEHIND THE SCENES';

#List films ordered by release year and title in alphabetical order.
SELECT TITLE FROM FILM ORDER BY RELEASE_YEAR AND TITLE ASC;

#Drop column picture from staff.
ALTER TABLE STAFF DROP COLUMN PICTURE;

#A new person is hired to help Jon. Her name is TAMMY SANDERS, and she is a customer. Update the database accordingly.
SELECT * FROM STAFF WHERE FIRST_NAME='JON';
SELECT * FROM CUSTOMER WHERE FIRST_NAME='TAMMY';
INSERT INTO STAFF (STAFF_ID, FIRST_NAME, LAST_NAME, ADDRESS_ID, EMAIL, STORE_ID, ACTIVE, USERNAME, PASSWORD, LAST_UPDATE) VALUES (3,'TAMMY', 'SANDERS', 79, 'TAMMY.SANDERS@sakilacustomer.org', 2, 1, 'TAMMY', NULL, '2006-02-15 04:57:20');
# Can't add "MAX(STAFF_ID)+1" to staff_id and it doesn't auto-increment... trash.
